version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   
    environment:
      - NODE_ENV=production 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
