version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: desafio-fullstack
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=desafio-fullstack-api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
